fos_rest:
    versioning:
        enabled: true
        resolvers:
            media_type: # Accept header
                enabled: true
                regex: '/(v|version)=(?P<version>[0-9\.]+)/'
    param_fetcher_listener: force
    body_converter:
        enabled: true
        validate: true
    disable_csrf_role: ROLE_API
    view:
        view_response_listener: force
        formats:
            xml: true
            json: true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        mime_types:
            json: ['application/json', 'application/json;version=0.2', 'application/json;version=2.0']

    routing_loader:
        include_format: false
        default_format: json

    format_listener:
        enabled: true
        rules:
            - { path: '^/api/', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: ^/, priorities: ['html', 'text/css' ,'*/*'], fallback_format: html, prefer_extension: true }
#            - { path: '^/api/', priorities: ['json', 'xml'], prefer_extension: false }

    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
            'Symfony\Component\HttpKernel\Exception\HttpException': true
            'Doctrine\ORM\OptimisticLockException': true